name: RadShacks
favicon: null
layout_spectrum: 0.6000359544996172
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#69919f'
    - '#adbbbc'
    - '#222a26'
    - '#405051'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
