name: RadShacks
favicon: null
layout_spectrum: 0.6000359544996172
typography_spectrum: 0.4833297096192837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.46332708233967423
  lightness: 0.7541853312868625
  saturation: 0.009240562561899424
  rhythmicContrast: 0.6526594064198434
purpose: []
